title boot
linux /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-cachyos-hardened
initrd /%INSTALL_DIR%/boot/x86_64/initramfs-linux-cachyos-hardened.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL%
